spring:
  redis:
    database: 0
    timeout: 6000
    password: 123456
    host: 192.168.0.59
    port: 6379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 10
        min-idle: 5
        max-wait: 3000